import { Bar, BarChart, CartesianGrid, ComposedChart, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { ReactNode } from 'react';
import type { deviationStats, statsRows, workoutWeeks, topFoods } from '../lib/stats';
import { displayDate } from '../lib/dates';

const grid = <CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false} />;
const tick = { fill: 'var(--muted)', fontSize: 11, fontFamily: 'Heebo Variable' };
const tooltipStyle = { background: 'var(--surface)', color: 'var(--text)', border: '1px solid var(--border)', borderRadius: 12, direction: 'rtl' as const };
const dateTick = (date: string) => displayDate(date, true);
const dateTooltip = (value: unknown) => typeof value === 'string' ? displayDate(value) : '';
function ChartCard({ title, children, note }: { title: string; children: ReactNode; note?: string }) {
  return <section className="card chart-card"><h2>{title}</h2>{note && <p className="muted small-text">{note}</p>}<div className="chart" dir="ltr">{children}</div></section>;
}
export default function StatsCharts({ rows, weeks, foods, deviations, weightGoal }: { deviations: ReturnType<typeof deviationStats>; rows: ReturnType<typeof statsRows>; weeks: ReturnType<typeof workoutWeeks>; foods: ReturnType<typeof topFoods>; weightGoal?: number }) {
  return <div className="stack">
    <ChartCard title="משקל לאורך הדרך" note="הממוצע מחושב מהשקילות בשבעת הימים האחרונים."><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{ left: -16, right: 12, top: 10 }}>{grid}<XAxis dataKey="date" tickFormatter={dateTick} tick={tick} minTickGap={35} /><YAxis domain={['auto', 'auto']} tick={tick} /><Tooltip contentStyle={tooltipStyle} labelFormatter={dateTooltip} /><Legend /><Line name="משקל (ק״ג)" dataKey="weight" stroke="var(--primary)" strokeWidth={3} connectNulls dot={{ r: 3 }} /><Line name="ממוצע 7 ימים" dataKey="average" stroke="var(--amber)" strokeDasharray="5 4" dot={false} connectNulls />{weightGoal !== undefined && <ReferenceLine y={weightGoal} stroke="var(--muted)" strokeDasharray="4 4" label={{ value: 'יעד', fill: 'var(--muted)', position: 'insideTopRight' }} />}</LineChart></ResponsiveContainer></ChartCard>
    <ChartCard title="עמידה יומית בתפריט"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{ left: -16, right: 12 }}>{grid}<XAxis dataKey="date" tickFormatter={dateTick} tick={tick} minTickGap={35} /><YAxis domain={[0, 100]} tick={tick} /><Tooltip contentStyle={tooltipStyle} labelFormatter={dateTooltip} /><Bar name="עמידה בתפריט (%)" dataKey="adherence" fill="var(--primary)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="בנק הקלוריות"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{ left: -16, right: 12 }}>{grid}<XAxis dataKey="date" tickFormatter={dateTick} tick={tick} minTickGap={35} /><YAxis tick={tick} /><Tooltip contentStyle={tooltipStyle} labelFormatter={dateTooltip} /><Legend /><Bar dataKey="spent" name="חיוב (קל׳)" fill="var(--amber)" radius={[4, 4, 0, 0]} /><Line dataKey="budget" name="תקציב" stroke="var(--primary)" dot={false} strokeDasharray="4 4" /></ComposedChart></ResponsiveContainer></ChartCard>
    <ChartCard title="חריגות לפי יום"><ResponsiveContainer width="100%" height="100%"><BarChart data={deviations.byDay} margin={{ left: -16, right: 12 }}>{grid}<XAxis dataKey="date" tickFormatter={dateTick} tick={tick} minTickGap={35} /><YAxis tick={tick} allowDecimals={false} /><Tooltip contentStyle={tooltipStyle} labelFormatter={dateTooltip} formatter={(value, _name, item) => [`${value} קל׳ · ${(item.payload as { count: number }).count} חריגות`, 'חריגות']} /><Bar name="חריגות (קל׳)" dataKey="kcal" fill="var(--danger)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>
    {deviations.categories.length > 0 && <ChartCard title="סוגי חריגות נפוצים"><ResponsiveContainer width="100%" height="100%"><BarChart data={deviations.categories} layout="vertical" margin={{ left: 4, right: 20 }}><XAxis type="number" tick={tick} allowDecimals={false} /><YAxis type="category" dataKey="name" tick={{ ...tick, fontSize: 10 }} width={125} tickFormatter={name => String(name).length > 23 ? `${String(name).slice(0, 23)}…` : String(name)} /><Tooltip contentStyle={tooltipStyle} /><Bar name="חריגות" dataKey="count" fill="var(--danger)" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></ChartCard>}
    <ChartCard title="כוסות מים ביום"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{ left: -16, right: 12 }}>{grid}<XAxis dataKey="date" tickFormatter={dateTick} tick={tick} minTickGap={35} /><YAxis tick={tick} allowDecimals={false} /><Tooltip contentStyle={tooltipStyle} labelFormatter={dateTooltip} /><Legend /><Bar name="כוסות" dataKey="water" fill="var(--water)" radius={[4, 4, 0, 0]} /><Line name="יעד שתייה" dataKey="waterGoal" stroke="var(--primary)" dot={false} strokeDasharray="4 4" /></ComposedChart></ResponsiveContainer></ChartCard>
    <ChartCard title="אימונים בשבוע"><ResponsiveContainer width="100%" height="100%"><BarChart data={weeks} margin={{ left: -16, right: 12 }}>{grid}<XAxis dataKey="date" tickFormatter={dateTick} tick={tick} minTickGap={35} /><YAxis tick={tick} allowDecimals={false} /><Tooltip contentStyle={tooltipStyle} labelFormatter={dateTooltip} /><Bar name="אימונים" dataKey="workouts" fill="var(--primary)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>
    {foods.map(group => <ChartCard key={group.component} title={`הבחירות המובילות · ${group.component}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={group.foods} layout="vertical" margin={{ left: 4, right: 20 }}><XAxis type="number" tick={tick} allowDecimals={false} /><YAxis type="category" dataKey="name" tick={{ ...tick, fontSize: 10 }} width={125} tickFormatter={name => String(name).length > 23 ? `${String(name).slice(0, 23)}…` : String(name)} /><Tooltip contentStyle={tooltipStyle} /><Bar name="בחירות" dataKey="count" fill="var(--primary)" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></ChartCard>)}
  </div>;
}
