-- Web Push: per-device subscriptions, per-user evening-summary preferences, and server-only config.

create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now()
);
create index push_subscriptions_user_idx on public.push_subscriptions (user_id);

create table public.notification_prefs (
  user_id uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  evening_enabled boolean not null default false,
  evening_time time not null default '21:30',
  timezone text not null default 'Asia/Jerusalem',
  -- Written by the app after each sync: the summary for summary_date (the user's local date).
  summary_date date,
  summary_title text,
  summary_body text,
  -- Written by the push function only, so each user gets at most one evening summary per local day.
  last_sent_date date,
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
alter table public.notification_prefs enable row level security;

create policy "push_subscriptions_select" on public.push_subscriptions for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "push_subscriptions_insert" on public.push_subscriptions for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "push_subscriptions_update" on public.push_subscriptions for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "push_subscriptions_delete" on public.push_subscriptions for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "notification_prefs_select" on public.notification_prefs for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "notification_prefs_insert" on public.notification_prefs for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "notification_prefs_update" on public.notification_prefs for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "notification_prefs_delete" on public.notification_prefs for delete to authenticated
  using ((select auth.uid()) = user_id);

grant select, insert, update, delete on table public.push_subscriptions, public.notification_prefs to authenticated;
revoke all on table public.push_subscriptions, public.notification_prefs from anon;

-- Server-only config (VAPID keys are generated by the push function on first use; never exposed).
-- RLS on with no policies + no grants: only the service role / secret key can read it.
create table public.push_config (
  id smallint primary key default 1 check (id = 1),
  vapid_keys jsonb,
  application_server_key text,
  cron_token text not null default encode(extensions.gen_random_bytes(32), 'hex')
);
alter table public.push_config enable row level security;
revoke all on table public.push_config from anon, authenticated;
insert into public.push_config (id) values (1);

-- Scheduler: pg_cron calls the push function every 5 minutes; the function decides who is due.
create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;
