import type { MealComponent, OptionGroup } from '../../types';
import { Field, NumberField, TextField, Toggle } from '../ui';
import { EditorActions } from './EditorActions';
import { moveItem } from '../../lib/reorder';
export function ComponentsEditor({ components, groups, onChange }: { components: MealComponent[]; groups: OptionGroup[]; onChange: (components: MealComponent[]) => void }) {
  const edit = (index: number, component: MealComponent) => onChange(components.map((c, i) => i === index ? component : c));
  return <div className="stack"><h3>מרכיבי הארוחה</h3>{components.map((component, index) => <details className="editor-item" key={component.id}><summary>{component.label || 'מרכיב ללא שם'}</summary><div className="stack editor-body"><TextField label="שם המרכיב" value={component.label} onChange={label => edit(index, { ...component, label })} /><Field label="סוג מרכיב"><select value={component.kind} onChange={e => edit(index, e.target.value === 'choice' ? { id: component.id, label: component.label, kind: 'choice', groupIds: [], pick: 1, required: true } : { id: component.id, label: component.label, kind: 'check' })}><option value="choice">בחירת מאכלים</option><option value="check">תוספת לסימון</option></select></Field>
    {component.kind === 'check' ? <TextField label="הערה" value={component.note} onChange={note => edit(index, { ...component, note })} /> : <><fieldset className="component"><legend>קבוצות מאכלים</legend>{groups.map(group => <Toggle key={group.id} label={group.name} checked={component.groupIds.includes(group.id)} onChange={checked => edit(index, { ...component, groupIds: checked ? [...component.groupIds, group.id] : component.groupIds.filter(id => id !== group.id), optionIds: checked ? component.optionIds : component.optionIds?.filter(id => !group.options.some(o => o.id === id)) })} />)}{component.groupIds.filter(id => !groups.some(g => g.id === id)).map(id => <Toggle key={id} label="(נמחק)" checked onChange={() => edit(index, { ...component, groupIds: component.groupIds.filter(g => g !== id) })} />)}</fieldset><fieldset className="component"><legend>הגבלה למאכלים מסוימים</legend><p className="muted small-text">ללא סימון מוצעים כל המאכלים של הקבוצות שנבחרו.</p>{groups.filter(g => component.groupIds.includes(g.id)).flatMap(g => g.options).map(option => <Toggle key={option.id} label={option.name} checked={!!component.optionIds?.includes(option.id)} onChange={checked => { const ids = checked ? [...(component.optionIds ?? []), option.id] : (component.optionIds ?? []).filter(id => id !== option.id); edit(index, { ...component, optionIds: ids.length ? ids : undefined }); }} />)}</fieldset><NumberField label="כמה מאכלים לבחור" min={1} value={component.pick} onChange={pick => edit(index, { ...component, pick: pick ?? 1 })} /><Toggle label="מרכיב חובה" checked={component.required} onChange={required => edit(index, { ...component, required })} /><TextField label="הערת כמות לארוחה" value={component.amountNote} onChange={amountNote => edit(index, { ...component, amountNote })} />
      <details className="overrides"><summary>כמויות מיוחדות לארוחה זו</summary><p className="muted small-text">שדה ריק משתמש בכמות הרגילה של המאכל.</p>{groups.filter(g => component.groupIds.includes(g.id)).flatMap(g => g.options).map(option => <TextField key={option.id} label={option.name} placeholder={option.amount} value={component.amountOverrides?.[option.id]} onChange={value => { const overrides = { ...component.amountOverrides }; if (value) overrides[option.id] = value; else delete overrides[option.id]; edit(index, { ...component, amountOverrides: overrides }); }} />)}</details></>}
    <EditorActions name={component.label} index={index} count={components.length} move={direction => { const next = [...components]; moveItem(next, index, direction); onChange(next); }} remove={() => onChange(components.filter(c => c.id !== component.id))} />
  </div></details>)}<button className="secondary-button" onClick={() => onChange([...components, { id: crypto.randomUUID(), label: 'מרכיב חדש', kind: 'choice', groupIds: [], pick: 1, required: true }])}>+ הוספת מרכיב</button></div>;
}
